config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resources :users

  get 'signing' => 'home#signing'

end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	after_create :set_slug
	has_many :messages


	def set_slug
		o = [('a'..'z'), (1..9), ('A'..'Z')].map { |i| i.to_a }.flatten
		string = (0...8).map { o[rand(o.length)] }.join
		self.slug =  name.gsub(' ', '-') + '-' + id.to_s + string
		self.save
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	# def signing
	# 	bucket = "YOUR_BUCKET_NAME",
 #    	awsKey = "YOUR_AWS_USER_KEY",
 #    	secret = "YOUR_AWS_USER_SECRET";

	#     var fileName = req.body.fileName,
	#     expiration = new Date(new Date().getTime() + 1000 * 60 * 5).toISOString();
	 
	#     var policy =
	#     { "expiration": expiration,
	#         "conditions": [
	#             {"bucket": bucket},
	#             {"key": fileName},
	#             {"acl": 'public-read'},
	#             ["starts-with", "$Content-Type", ""],
	#             ["content-length-range", 0, 524288000]
	#         ]};
	 
	#     policyBase64 = new Buffer(JSON.stringify(policy), 'utf8').toString('base64');
	#     signature = crypto.createHmac('sha1', secret).update(policyBase64).digest('base64');
	#     res.json({bucket: bucket, awsKey: awsKey, policy: policyBase64, signature: signature});
	# end
	 # create the document in rails, then send json back to our javascript to populate the form that will be
	  # going to amazon.
	  def signing
	    @document = Document.create(params[:doc])
	    render :json => {
	      :policy => s3_upload_policy_document, 
	      :signature => s3_upload_signature, 
	      :key => @document.s3_key, 
	      :success_action_redirect => document_upload_success_document_url(@document)
	    }
	  end


	 # generate the policy document that amazon is expecting.
	  def s3_upload_policy_document
	    return @policy if @policy
	    ret = {"expiration" => 5.minutes.from_now.utc.xmlschema,
	      "conditions" =>  [ 
	        {"bucket" =>  YOUR_BUCKET_NAME}, 
	        ["starts-with", "$key", @document.s3_key],
	        {"acl" => "private"},
	        {"success_action_status" => "200"},
	        ["content-length-range", 0, 1048576]
	      ]
	    }
	    @policy = Base64.encode64(ret.to_json).gsub(/\n/,'')
	  end

	  # sign our request by Base64 encoding the policy document.
	  def s3_upload_signature
	    signature = Base64.encode64(OpenSSL::HMAC.digest(OpenSSL::Digest::Digest.new('sha1'), YOUR_SECRET_KEY, s3_upload_policy_document)).gsub("\n","")
	  end
end

# var s3Uploader = (function () {
 
#     var signingURI = "/signing";
 
#     function upload(imageURI, fileName) {
 
#         var deferred = $.Deferred(),
#             ft = new FileTransfer(),
#             options = new FileUploadOptions();
 
#         options.fileKey = "file";
#         options.fileName = fileName;
#         options.mimeType = "image/jpeg";
#         options.chunkedMode = false;
 
#         $.ajax({url: signingURI, data: {"fileName": fileName}, dataType: "json", type: "POST"})
#             .done(function (data) {
#                 options.params = {
#                     "key": fileName,
#                     "AWSAccessKeyId": data.awsKey,
#                     "acl": "public-read",
#                     "policy": data.policy,
#                     "signature": data.signature,
#                     "Content-Type": "image/jpeg"
#                 };
 
#                 ft.upload(imageURI, "https://" + data.bucket + ".s3.amazonaws.com/",
#                     function (e) {
#                         deferred.resolve(e);
#                     },
#                     function (e) {
#                         alert("Upload failed");
#                         deferred.reject(e);
#                     }, options);
 
#             })
#             .fail(function (error) {
#                 console.log(JSON.stringify(error));
#             });
#              return deferred.promise();
 
#     }
 
#     return {
#         upload: upload
#     }
 
# }());

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: 'Message was successfully created.' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:sender_id, :receiver_id, :msg_type, :msg_text, :attachment_url, :attachment_ext)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :mobile, :active, :slug, :user_type, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dopac</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/messages/_form.html.erb
<%= form_for(@message) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sender_id %><br>
    <%= f.number_field :sender_id %>
  </div>
  <div class="field">
    <%= f.label :receiver_id %><br>
    <%= f.number_field :receiver_id %>
  </div>
  <div class="field">
    <%= f.label :msg_type %><br>
    <%= f.text_field :msg_type %>
  </div>
  <div class="field">
    <%= f.label :msg_text %><br>
    <%= f.text_area :msg_text %>
  </div>
  <div class="field">
    <%= f.label :attachment_url %><br>
    <%= f.text_field :attachment_url %>
  </div>
  <div class="field">
    <%= f.label :attachment_ext %><br>
    <%= f.text_field :attachment_ext %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Messages</h1>

<table>
  <thead>
    <tr>
      <th>Sender</th>
      <th>Receiver</th>
      <th>Msg type</th>
      <th>Msg text</th>
      <th>Attachment url</th>
      <th>Attachment ext</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.sender_id %></td>
        <td><%= message.receiver_id %></td>
        <td><%= message.msg_type %></td>
        <td><%= message.msg_text %></td>
        <td><%= message.attachment_url %></td>
        <td><%= message.attachment_ext %></td>
        <td><%= link_to 'Show', message %></td>
        <td><%= link_to 'Edit', edit_message_path(message) %></td>
        <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Message', new_message_path %>

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form' %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sender:</strong>
  <%= @message.sender_id %>
</p>

<p>
  <strong>Receiver:</strong>
  <%= @message.receiver_id %>
</p>

<p>
  <strong>Msg type:</strong>
  <%= @message.msg_type %>
</p>

<p>
  <strong>Msg text:</strong>
  <%= @message.msg_text %>
</p>

<p>
  <strong>Attachment url:</strong>
  <%= @message.attachment_url %>
</p>

<p>
  <strong>Attachment ext:</strong>
  <%= @message.attachment_ext %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :mobile %><br>
    <%= f.text_field :mobile %>
  </div>
  <div class="field">
    <%= f.label :active %><br>
    <%= f.check_box :active %>
  </div>
  <div class="field">
    <%= f.label :slug %><br>
    <%= f.text_field :slug %>
  </div>
  <div class="field">
    <%= f.label :user_type %><br>
    <%= f.text_field :user_type %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Mobile</th>
      <th>Active</th>
      <th>Slug</th>
      <th>User type</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.mobile %></td>
        <td><%= user.active %></td>
        <td><%= user.slug %></td>
        <td><%= user.user_type %></td>
        <td><%= user.image %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Mobile:</strong>
  <%= @user.mobile %>
</p>

<p>
  <strong>Active:</strong>
  <%= @user.active %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @user.slug %>
</p>

<p>
  <strong>User type:</strong>
  <%= @user.user_type %>
</p>

<p>
  <strong>Image:</strong>
  <%= @user.image %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>